[project]
name = "aligned_textgrid"
packages = [{include = "aligned_textgrid", from="src"}]
version = "0.8.2a1"
description = "Classes for defining sequential information from TextGrids"
authors = [
  {name="Josef Fruehwald", email = "JoFrhwld@gmail.com>"}, 
  {name="chrisbrickhouse", email = "brickhouse@stanford.edu"}
]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://forced-alignment-and-vowel-extraction.github.io/alignedTextGrid/"
repository = "https://github.com/Forced-Alignment-and-Vowel-Extraction/alignedTextGrid"
requires-python = ">=3.10"
dependencies = [
    "cloudpickle>=3.1.2",
    "numpy>=2.2.6",
    "polars>=1.39.3",
    "praatio>=6.2.2",
    "toml>=0.10.2",
]

[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
docs = [
    "jupyter>=1.1.1",
    "quartodoc>=0.11.1",
    "textgrid>=1.6.1",
]
test = [
    "codecov>=2.1.13",
    "importlib>=1.0.4",
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
    "pytest-html>=4.2.0",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--cov-config=.coveragerc",
    "--cov-report=xml",
    "--cov"
]
filterwarnings =[
    "ignore::UserWarning"
]
pythonpath = "src"
testpaths = "tests"
