# Function reference

## Sequence Classes

These classes define attributes and methods for Intervals 
and Points.


### Common Features

These classes define common attributes and methods available
to intervals and points.


| | |
| --- | --- |
| [PrecedenceMixins](PrecedenceMixins.qmd#aligned_textgrid.mixins.mixins.PrecedenceMixins) | Methods and attributes for SequenceIntervals and SequencePoints |
| [InTierMixins](InTierMixins.qmd#aligned_textgrid.mixins.mixins.InTierMixins) | Methods and attrubites relating `Sequence*` objects to tiers. |

### Intervals

The basic `SequenceInterval` class and special `Top` and `Bottom` classes.
For customized `SequenceIntervals`, see [Word](Word.qmd) and [Phone](Phone.qmd),
or [`custom_classes()`](custom_classes.qmd).


| | |
| --- | --- |
| [SequenceInterval](SequenceInterval.qmd#aligned_textgrid.sequences.sequences.SequenceInterval) | A class to describe an interval with precedence relationships and hierarchical relationships |
| [Top](Top.qmd#aligned_textgrid.sequences.sequences.Top) | A top level interval class |
| [Bottom](Bottom.qmd#aligned_textgrid.sequences.sequences.Bottom) | A bottom level interval class |

### Points

There is just a single SequencePoint class, since points
don't have hierarchical relationships defined.


| | |
| --- | --- |
| [SequencePoint](SequencePoint.qmd#aligned_textgrid.points.points.SequencePoint) | Sequence Points |

## Tiers

Tiers Classes

### Common Features

These classes define common attributes and methods shared accross
all tier and tiergroups.


| | |
| --- | --- |
| [TierMixins](TierMixins.qmd#aligned_textgrid.mixins.tiermixins.TierMixins) | Methods and attributes for Sequence Tiers |
| [TierGroupMixins](TierGroupMixins.qmd#aligned_textgrid.mixins.tiermixins.TierGroupMixins) | Methods and attributes for grouped tiers |

### Tiers and Tier Groups

These classes define tiers and tier groups.


| | |
| --- | --- |
| [SequenceTier](SequenceTier.qmd#aligned_textgrid.sequences.tiers.SequenceTier) | A sequence tier |
| [SequencePointTier](SequencePointTier.qmd#aligned_textgrid.points.tiers.SequencePointTier) | A SequencePointTier class |
| [TierGroup](TierGroup.qmd#aligned_textgrid.sequences.tiers.TierGroup) | Tier Grouping |

## TextGrids

TextGrid Classes

| | |
| --- | --- |
| [AlignedTextGrid](AlignedTextGrid.qmd#aligned_textgrid.aligned_textgrid.AlignedTextGrid) | An aligned Textgrid |

## Custom Classes

Custom Classes

### Custom Class Creation

This is a function that will quickly create custom classes
- package: aligned_textgrid.custom_classes
  name: custom_classes


### Word and Phone Classes

These are mostly intended to be used with textgrids that are the 
product of forced alignment.


| | |
| --- | --- |
| [Word](Word.qmd#aligned_textgrid.sequences.word_and_phone.Word) | A Word subclass of SequenceInterval |
| [Phone](Phone.qmd#aligned_textgrid.sequences.word_and_phone.Phone) | A Phone subclass of SequenceInterval |

### PoLaR Classes

These are classes intended to make it easier to work with
PoLaR annotation.


| | |
| --- | --- |
| [PrStr](PrStr.qmd#aligned_textgrid.polar.polar_classes.PrStr) | PrStr tier points |
| [ToBI](ToBI.qmd#aligned_textgrid.polar.polar_classes.ToBI) | A ToBI point class |
| [ToBI](ToBI.qmd#aligned_textgrid.polar.polar_classes.ToBI) | A ToBI point class |
| [TurningPoints](TurningPoints.qmd#aligned_textgrid.polar.polar_classes.TurningPoints) | A turning point class |
| [Ranges](Ranges.qmd#aligned_textgrid.polar.polar_classes.Ranges) | A ranges interval |
| [Levels](Levels.qmd#aligned_textgrid.polar.polar_classes.Levels) | A levels point class |
| [Misc](Misc.qmd#aligned_textgrid.polar.polar_classes.Misc) | Misc points |

## DataFrame outputs

This will return a polars dataframe given an `aligned_textgrid`
object


| | |
| --- | --- |
| [to_df](to_df.qmd#aligned_textgrid.outputs.to_dataframe.to_df) | Return an `aligned_textgrid` object as a dataframe |