# SequencePointTier { #aligned_textgrid.points.tiers.SequencePointTier }

`points.tiers.SequencePointTier(self, tier=[], entry_class=SequencePoint)`

A SequencePointTier class

## Parameters

| Name          | Type                       | Description                                                | Default         |
|---------------|----------------------------|------------------------------------------------------------|-----------------|
| `tier`        | PointTier \| list\[Point\] | Either a `praatio` PointTier or a list of `praatio` Points | `[]`            |
| `entry_class` | Type\[SequencePoint\]      | A SequencePoint subclass                                   | `SequencePoint` |

## Attributes

| Name        | Type                  | Description                                       |
|-------------|-----------------------|---------------------------------------------------|
| ...         |                       | All attributes and methods included in TierMixins |
| entry_class | Type\[SequencePoint\] | The class of entries within the tier              |
| name        | str                   | The name of the tier                              |
| times       | np.array              | The times of points in the tier                   |
| labels      | list\[str, ...\]      | The labels of points in the tier                  |
| xmin        | float                 | The time of the first point in the tier           |
| xmax        | float                 | The time of the last point in the tier            |
| \[\]        | float                 | Indexable and iterable                            |

## Methods

| Name | Description |
| --- | --- |
| [get_nearest_point](#aligned_textgrid.points.tiers.SequencePointTier.get_nearest_point) | _Returns nearest point_ |
| [get_nearest_point_index](#aligned_textgrid.points.tiers.SequencePointTier.get_nearest_point_index) | Returns the index of the closest point to `time` |
| [return_tier](#aligned_textgrid.points.tiers.SequencePointTier.return_tier) | Returns SequencePointTier as a `praatio` PointTier |
| [save_as_tg](#aligned_textgrid.points.tiers.SequencePointTier.save_as_tg) | Saves the current point tier as a textgrid |

### get_nearest_point { #aligned_textgrid.points.tiers.SequencePointTier.get_nearest_point }

`points.tiers.SequencePointTier.get_nearest_point(time)`

_Returns nearest point_

#### Parameters

| Name   | Type   | Description                            | Default    |
|--------|--------|----------------------------------------|------------|
| `time` | float  | time at which to get the nearest point | _required_ |

#### Returns

| Type          | Description                 |
|---------------|-----------------------------|
| SequencePoint | the nearest point to `time` |

### get_nearest_point_index { #aligned_textgrid.points.tiers.SequencePointTier.get_nearest_point_index }

`points.tiers.SequencePointTier.get_nearest_point_index(time)`

Returns the index of the closest point to `time`

#### Parameters

| Name   | Type   | Description                                | Default    |
|--------|--------|--------------------------------------------|------------|
| `time` | float  | The time at which to get the nearest point | _required_ |

#### Returns

| Type   | Description                                    |
|--------|------------------------------------------------|
| int    | The index of the nearest point within the tier |

### return_tier { #aligned_textgrid.points.tiers.SequencePointTier.return_tier }

`points.tiers.SequencePointTier.return_tier()`

Returns SequencePointTier as a `praatio` PointTier

#### Returns

| Type      | Description            |
|-----------|------------------------|
| PointTier | A `praatio` point tier |

### save_as_tg { #aligned_textgrid.points.tiers.SequencePointTier.save_as_tg }

`points.tiers.SequencePointTier.save_as_tg(save_path)`

Saves the current point tier as a textgrid

#### Parameters

| Name        | Type   | Description                                  | Default    |
|-------------|--------|----------------------------------------------|------------|
| `save_path` | str    | path to where you want to save the textgrid. | _required_ |