# SequencePoint { #aligned_textgrid.points.points.SequencePoint }

`points.points.SequencePoint(self, point=Point(0, ''))`

_A point class_

## Parameters

| Name    | Type   | Description                | Default        |
|---------|--------|----------------------------|----------------|
| `point` | Point  | _a `praatio` point object_ | `Point(0, '')` |

## Attributes

| Name          | Type              | Description                                                                                 |
|---------------|-------------------|---------------------------------------------------------------------------------------------|
| ...           |                   | All attributes and methods included in PrecedenceMixins and InTierMixins                    |
| time          | float             | Time value associated with the point.                                                       |
| label         | str               | Label associated with the point                                                             |
| intier        | SequencePointTier | If the SequencePoint is within a tier, this accesses the tier.                              |
| fol           | SequencePoint     | If defined, the following SequencePoint within the same tier                                |
| prev          | SequencePoint     | If defined, the previous SequencePoint within the same tier.                                |
| fol_distance  | float             | If `fol` is defined, the difference between the current point and `fol` (should be >= 0)    |
| prev_distance | float             | if `prev` is defined, the difference between the current point and `prev` (should be <= 0). |

## Methods

| Name | Description |
| --- | --- |
| [distance_from](#aligned_textgrid.points.points.SequencePoint.distance_from) | _distance from an entry_ |
| [get_interval_at_point](#aligned_textgrid.points.points.SequencePoint.get_interval_at_point) | _Get the SequenceInterval the current point falls within_ |
| [get_interval_index_at_time](#aligned_textgrid.points.points.SequencePoint.get_interval_index_at_time) | _Get the index of an interval at the point's time_ |

### distance_from { #aligned_textgrid.points.points.SequencePoint.distance_from }

`points.points.SequencePoint.distance_from(entry)`

_distance from an entry_

#### Parameters

| Name    | Type                     | Description                                                           | Default    |
|---------|--------------------------|-----------------------------------------------------------------------|------------|
| `entry` | Self \| SequenceInterval | A point or an interval to get the distance of the current  point from | _required_ |

#### Returns

| Type                     | Description                                                                      |
|--------------------------|----------------------------------------------------------------------------------|
| Union\[float, np.array\] | a single value in the case of a point, a numpy array in the case of an interval. |

### get_interval_at_point { #aligned_textgrid.points.points.SequencePoint.get_interval_at_point }

`points.points.SequencePoint.get_interval_at_point(tier=None)`

_Get the SequenceInterval the current point falls within_

#### Parameters

| Name   | Type         | Description                                                            | Default   |
|--------|--------------|------------------------------------------------------------------------|-----------|
| `tier` | SequenceTier | The sequence tier within which to look for a matching SequenceInterval | `None`    |

#### Returns

| Type             | Description                                               |
|------------------|-----------------------------------------------------------|
| SequenceInterval | The SequenceInterval within which the current point falls |

### get_interval_index_at_time { #aligned_textgrid.points.points.SequencePoint.get_interval_index_at_time }

`points.points.SequencePoint.get_interval_index_at_time(tier=None)`

_Get the index of an interval at the point's time_

#### Parameters

| Name   | Type         | Description     | Default   |
|--------|--------------|-----------------|-----------|
| `tier` | SequenceTier | A SequenceTier. | `None`    |

#### Returns

| Type   | Description                                                    |
|--------|----------------------------------------------------------------|
| int    | The index of the SequenceInterval within which the point falls |