# TierGroup { #aligned_textgrid.sequences.tiers.TierGroup }

`sequences.tiers.TierGroup(self, tiers=[SequenceTier()])`

Tier Grouping

## Parameters

| Name    | Type                 | Description                                                                                 | Default            |
|---------|----------------------|---------------------------------------------------------------------------------------------|--------------------|
| `tiers` | list\[SequenceTier\] | A list of sequence tiers that are  meant to be in hierarchical relationships with eachother | `[SequenceTier()]` |

## Attributes

| Name          | Type                             | Description                                    |
|---------------|----------------------------------|------------------------------------------------|
| tier_list     | list\[SequenceTier\]             | List of sequence tiers that have been related. |
| entry_classes | list\[Type\[SequenceInterval\]\] | A list of the entry classes for each tier.     |
| tier_names    | list\[str\]                      | A list of tier names                           |
| xmax          | float                            | Maximum time                                   |
| xmin          | float                            | Minimum time                                   |
| \[\]          |                                  | Indexable. Returns a SequenceTier              |

## Methods

| Name | Description |
| --- | --- |
| [get_intervals_at_time](#aligned_textgrid.sequences.tiers.TierGroup.get_intervals_at_time) | Get intervals at time |
| [shift](#aligned_textgrid.sequences.tiers.TierGroup.shift) | Shift the start and end times of all intervals within |
| [show_structure](#aligned_textgrid.sequences.tiers.TierGroup.show_structure) | Show the hierarchical structure |

### get_intervals_at_time { #aligned_textgrid.sequences.tiers.TierGroup.get_intervals_at_time }

`sequences.tiers.TierGroup.get_intervals_at_time(time)`

Get intervals at time

Returns a list of intervals at `time` for each tier.

#### Parameters

| Name   | Type   | Description       | Default    |
|--------|--------|-------------------|------------|
| `time` | float  | Time in intervals | _required_ |

#### Returns

| Type        | Description                                                  |
|-------------|--------------------------------------------------------------|
| list\[int\] | A list of interval indices, one for each tier in `tier_list` |

### shift { #aligned_textgrid.sequences.tiers.TierGroup.shift }

`sequences.tiers.TierGroup.shift(increment)`

Shift the start and end times of all intervals within
the TierGroup by the increment size

#### Parameters

| Name        | Type   | Description                                                                                            | Default    |
|-------------|--------|--------------------------------------------------------------------------------------------------------|------------|
| `increment` | float  | The time increment by which to shift the intervals within the TierGroup. Could be positive or negative | _required_ |

### show_structure { #aligned_textgrid.sequences.tiers.TierGroup.show_structure }

`sequences.tiers.TierGroup.show_structure()`

Show the hierarchical structure