# TierMixins { #aligned_textgrid.mixins.tiermixins.TierMixins }

`mixins.tiermixins.TierMixins()`

Methods and attributes for Sequence Tiers

## Attributes

| Name   | Type             | Description                  |
|--------|------------------|------------------------------|
| \[\]   |                  | indexable and iterable       |
| first  | SequenceInterval | The first entry in the tier. |
| last   | SequenceInterval | The last entry in the tier.  |

## Methods

| Name | Description |
| --- | --- |
| [index](#aligned_textgrid.mixins.tiermixins.TierMixins.index) | Return index of a tier entry |

### index { #aligned_textgrid.mixins.tiermixins.TierMixins.index }

`mixins.tiermixins.TierMixins.index(entry)`

Return index of a tier entry

#### Parameters

| Name    | Type                              | Description                                                | Default    |
|---------|-----------------------------------|------------------------------------------------------------|------------|
| `entry` | SequencePoint \| SequenceInterval | A SequenceInterval or a PointInterval to get the index of. | _required_ |

#### Returns

| Type   | Description       |
|--------|-------------------|
| int    | The entry's index |