name: Dev Tag

on:        
  pull_request:
    types:
      - closed
    branches:
      - 'dev'

jobs:
  dev-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7    
        with:
          enable-cache: true   
          python-version: "3.12"          
      - name: Bump Version
        run: echo "PKG_VERSION=$(uv version --bump alpha | awk '{print $2}')" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.PKG_VERSION }}
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ env.PKG_VERSION }}
      - name: Push Dev Version
        run: |
          git config --global user.name "Dev Tagger"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.PKG_VERSION }}"
          git push