name: Python CI

on:
  push:
    branches: [ $default-branch, "main", "dev", "workflows" ]
  pull_request:
    branches: [ $default-branch, "main", "dev", "feature/**", "release/**" ]

defaults:
  run:
    shell: bash
jobs:
  lint-and-test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Install project
      run: uv sync --group test
    - name: Test with pytest
      run: uv run pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}    